import assert from "node:assert/strict";
import { describe, it } from "node:test";

import {
  applyBlakePipeSizing,
  countElbowsMetres,
  isRightAngleBendMetres,
  summariseHeatingFittings,
} from "./blake-route";
import { heatingLayoutToStudio } from "./takeoff-export";
import type { HeatingSystemLayout } from "./types";

function sampleLayout(): HeatingSystemLayout {
  return {
    systemOptionId: "gas-system",
    emitterMode: "radiators",
    updatedAt: new Date().toISOString(),
    plants: [
      { id: "p1", kind: "boiler", label: "Gas boiler", x: 1, y: 1, floorLevel: "ground" },
      { id: "p2", kind: "cylinder", label: "210L cylinder", x: 1.8, y: 1, floorLevel: "ground" },
      { id: "p3", kind: "manifold", label: "Manifold", x: 2.6, y: 1, floorLevel: "ground" },
    ],
    emitters: [
      {
        id: "e1",
        kind: "radiator",
        label: "Living rad",
        roomId: "r1",
        x: 5,
        y: 3,
        widthM: 1.2,
        depthM: 0.1,
        rotationDeg: 0,
        floorLevel: "ground",
      },
    ],
    pipes: [
      {
        id: "pipe-primary",
        kind: "primary",
        label: "Boiler → cylinder",
        floorLevel: "ground",
        points: [
          { x: 1, y: 1 },
          { x: 1.8, y: 1 },
        ],
      },
      {
        id: "pipe-main",
        kind: "primary",
        label: "Cylinder → manifold",
        floorLevel: "ground",
        points: [
          { x: 1.8, y: 1 },
          { x: 2.6, y: 1 },
        ],
      },
      {
        id: "pipe-flow",
        kind: "flow",
        label: "Flow → Living rad",
        floorLevel: "ground",
        points: [
          { x: 2.6, y: 1 },
          { x: 5, y: 1 },
          { x: 5, y: 3 },
        ],
      },
      {
        id: "pipe-return",
        kind: "return",
        label: "Return ← Living rad",
        floorLevel: "ground",
        points: [
          { x: 5.1, y: 3 },
          { x: 5.1, y: 1.1 },
          { x: 2.7, y: 1.1 },
        ],
      },
    ],
  };
}

describe("heat design blake routes", () => {
  it("detects metre-space elbows", () => {
    assert.equal(
      isRightAngleBendMetres({ x: 0, y: 0 }, { x: 2, y: 0 }, { x: 2, y: 1.5 }),
      true,
    );
    assert.equal(countElbowsMetres([
      { x: 0, y: 0 },
      { x: 2, y: 0 },
      { x: 2, y: 1.5 },
    ]), 1);
  });

  it("sizes mains 28 and rad tails 15", () => {
    const sized = applyBlakePipeSizing(sampleLayout());
    const primary = sized.pipes.find((pipe) => pipe.id === "pipe-primary");
    const flow = sized.pipes.find((pipe) => pipe.id === "pipe-flow");
    assert.equal(primary?.diameterMm, 28);
    assert.equal(flow?.diameterMm, 15);
  });

  it("summarises elbows, couplings and reducers", () => {
    const summary = summariseHeatingFittings(sampleLayout());
    assert.ok(summary.totalMetres > 5);
    assert.ok(summary.totalElbows >= 2);
    assert.ok(summary.totalReducers >= 1);
    assert.ok(summary.bySize.some((row) => row.diameterMm === 28));
    assert.ok(summary.bySize.some((row) => row.diameterMm === 15));
  });

  it("exports sized studio geometries for takeoff", () => {
    const { studio, fittings } = heatingLayoutToStudio(sampleLayout());
    assert.ok(fittings.totalElbows >= 2);
    assert.ok(studio.scales.some((row) => row.documentId === "heat-design-plan"));
    const linears = studio.geometries.filter((geo) => geo.kind === "linear");
    assert.ok(linears.length >= 4);
    assert.ok(linears.every((geo) => geo.kind === "linear" && geo.diameter));
    assert.ok(studio.geometries.some((geo) => geo.kind === "count" && geo.classificationId === "cls-ai-P-BOILER"));
    assert.ok(studio.geometries.some((geo) => geo.kind === "count" && geo.autoGenerated));
  });
});
