import { NextResponse } from "next/server";

import { openAiKeySource, resolveOpenAiApiKey } from "@/lib/openai-env";
import { getServerStoreBackend } from "@/lib/server-store";
import { readDayworkSheetsStore } from "@/lib/daywork-sheets-store";
import { readDayworkWriteLog } from "@/lib/daywork-write-log";

export async function GET() {
  let dayworkSheetCount = 0;
  let dayworkSignedCount = 0;
  try {
    const sheets = Object.values(readDayworkSheetsStore());
    dayworkSheetCount = sheets.length;
    dayworkSignedCount = sheets.filter(
      (sheet) => Boolean(String(sheet.plumberSignature || "").trim() && String(sheet.clientSignature || "").trim()),
    ).length;
  } catch {
    // Best-effort diagnostics only.
  }

  const writeLog = readDayworkWriteLog();
  const lastWrite = writeLog.attempts[0] || null;
  const openaiConnected = Boolean(resolveOpenAiApiKey());
  const openaiSource = openAiKeySource();

  return NextResponse.json({
    ok: true,
    app: "nexa",
    store: getServerStoreBackend(),
    openai: {
      connected: openaiConnected,
      source: openaiSource,
    },
    deployment: {
      branch: process.env.RENDER_GIT_BRANCH ?? "local",
      commit: process.env.RENDER_GIT_COMMIT ?? "local",
      service:
        process.env.RENDER_SERVICE_NAME ||
        (process.env.NEXT_PUBLIC_APP_URL?.includes("nexa-live")
          ? "nexa-live"
          : process.env.NEXT_PUBLIC_APP_URL?.includes("nexa-pilot")
            ? "nexa-pilot"
            : "local"),
      appUrl: process.env.NEXT_PUBLIC_APP_URL ?? null,
      talkLab: "/field/talk-lab",
      talkLabBuild: "realtime-voice-picker-v1",
      heatDesign: "/heat-design",
      heatDesignBuild: "remove-core-heat-calc-tab-v1",
      heatDesignPersistence: "server-projects-v1",
      heatDesignAudit: "revisions-v1",
      fieldApp: "/field",
      fieldCoreLinked: true,
      fieldOfflineOutbox: "v1",
      reportsBoardPack: "pdf-excel-v1",
      invoicePortal: "public-token-v1",
      clientPortalHub: "v1",
      tenOfTenPlan: "phase-4-ten-of-ten-v1",
      portalHandoffAuthority: "quote-centres-variation-email-v1",
      fieldOfflineDayComplete: "outbox-outcome-hours-v1",
      reportsTrustPack: "manager-board-pack-v1",
      opsChainContinuity: "complete-passaround-invoice-merge-v2",
      dailyPathSimproOptional: "optional-sync-v1",
      sumupPayLinks: "hosted-checkout-v1",
      cashReconcile: "xero-filter-pull-v1",
      moneyPathContinuity: "sumup-xero-payment-merge-v1",
      xeroSalesAccountCodes: "finance-map-v1",
      collectionsOfflinePdf: "statement-remittance-chase-v1",
      siteCommercialTerms: "client-site-v1",
      retentionLedger: "cap-portfolio-report-v1",
      fieldServiceWorker: "shell-v2-scoped",
      dispatchRunSheet: "travel-buffer-v1",
      boardPackEmail: "monday-cron-v1",
      photoCompressBuild: "shrink-v1",
      blakeAccent: "picker-v1",
      blakePeerEngineer: "v1",
      blakeTrainer: "/train",
      blakeTrainerBuild: "continuous-conversation-v1",
      fieldHoursBuild: "time-check-v1",
      checklistUi: "tidy-v1",
      fieldCoreLive: "people-directory-az-v1",
      directoryBulkSelect: "v2-archive",
      peopleDirectoryAz: "search-az-firstname-v1",
      setupMobileScroll: "v1",
      simproDeepPull: "quotes-jobs-invoices-cc-schedules-v4",
      simproPreviewQuality: "conflicts-v1",
      simproSchedulePush: "managers-diary-v1",
      schedulesDiaryOpen: "click-timeline-v1",
      simproImportQuality: "quote-cc-info-and-cost-v1",
      simproCustomerNames: "display-all-full-entity-v4",
      simproImportOrphanLinks: "prune-reimport-v1",
      simproClientsFullFetch: "newest-80-v1",
      simproEntityFullFetch: "scoped-open-quotes-live-jobs-80-unpaid-v2",
      simproImportScope: "clients-sites-80-leads-10-quotes-30-jobs-80-deep-80-v7",
      simproLeadsImport: "latest-10-open-stage-status-v2",
      simproEodRefresh: "weekday-1800-utc-cron-v1",
      actionAlertsRouting: "folders-and-daywork-signoff-v1",
      personalisingBranding: "square-app-icons-v5-wordmark",
      browserTabFavicon: "ewg-wordmark-tab-v1",
      deployFix: "duplicate-messagecircle-import-v1",
      customiseForms: "delete-copy-colour-all-v1",
      uiModuleBarIpad: "scroll-and-pin-setup-v1",
      uiSetupScrollIpad: "workspace-scroll-1366-v1",
      uiSearchBrandBlue: "nexa-cyan-v1",
      uiSetupSaveButton: "no-stuck-saving-v2",
      uiNoNexaRailLogo: "owner-logo-only-v1",
      descriptionRichText: "toolbar-scripts-v1",
      quoteCatalogueOnQuote: "all-groups-on-quote-v1",
      quoteCostCentrePartsScope: "active-centre-only-v1",
      surveySendToQuote: "unpriced-rfq-allowed-v1",
      simproSiteHydrate: "fetch-by-site-id-v1",
      nexaTopBusyBar: "expand-contract-side-v3",
      quoteListTitleClamp: "one-line-v1",
      quoteListCostCentreCount: "v1",
      quoteImportPath: "same-as-job-scheduler-fetchFullEntity-v1",
      quoteDetail404Fix: "multi-company-no-slash-v1",
      quoteWrongCustomerFix: "no-list-fallback-row-v3",
      quoteCostPriceDistinct: "reject-mirrored-cost-v3",
      quoteCatalogCostPull: "nested-catalog-labor-stock-v2",
      quoteHeaderTotal: "keep-simpro-total-v1",
      quoteDeepCap: "deep-40-prioritise-incomplete-v1",
      quoteCcInfoRefresh: "incomplete-centres-repull-v1",
      quoteHubMergeCost: "prefer-server-distinct-cost-v1",
      uiSchedulerAvailability: "card-authoritative-v2",
      uiOverviewGantt: "booking-labels-v2",
      uiTopBarModules: "recurring-reports-stock-xero-v1",
      jobPriceFlickerFix: "keep-simpro-job-total-v1",
      aclDefaultDeny: "read-only-missing-role-v1",
      schedulerPeople: "employees-contractors-not-suppliers-v1",
      peopleDirectoryCrud: "manual-add-edit-v1",
      invoiceImportFolders: "sent-unpaid-overdue-v1",
      jobFoldersPassaround: "complete-then-ready-v2",
      recurringStockEdit: "edit-remove-v1",
      resetWorkflowRemoved: "no-accidental-wipe-v1",
      dashboardLayout: "pipeline-gantt-v3",
      coreUiPerf: "lazy-panels-boot-shell-v1",
      coreRoutes: "url-modules-v1",
      visualQa: "logo-rail-xero-finance-v1",
      platformPolish: "fifteen-pass-v1",
      fieldPhotoSync: "bytes-v1",
      fieldChrome: "no-connect-talk-v1",
      setupLabourForms: "types-certs-form-picker-v1",
      accountingSetup: "finance-home-v3",
      mobileNavFix: "url-sync-off-v5",
      moduleTabButtons: "unstyled-v1",
      heatDesignPlan: "save-race-walls-v1",
      heatDesignBlakeRoutes: "size-fittings-takeoff-v1",
      heatDesignBlakeKit: "ancillaries-valves-v1",
      heatDesignBlakeAi: "live-propose-v1",
      heatDesignBlakeLayout: "seed-from-ai-v1",
      aiSpine: "heat-takeoff-handoff-v1",
      takeoffBlakeProposeAi: "placement-v1",
      guidePrices: "rate-library-v1",
      blakeBudgetPrices: "openai-uk-trade-v1",
      premiumPolish: "core-survey-field-v1",
      heatDesignMobile: "core-nav-iphone-v1",
      routeAudit: "handoffs-core-nav-v1",
      priceLedger: "budget-guide-rfq-firm-v1",
      leadsRecordFix: "lead-quote-map-tdz-v1",
      e2eTestJobs: "numbered-pilot-jobs-v1",
      opsHarden: "backup-restore-openai-dualpath-v1",
      pilotBackup: "export-verify-dryrun-v2",
      openaiOps: "status-smoke-hasinapp-v1",
      dualPathCleanup: "ai-first-redirect-survey-canonical-v1",
      companyProd: "restore-firedrill-simpro-optional-v1",
      restoreFireDrill: "shadow-roundtrip-v1",
      earlyAccessPack: "company-production-v1",
      opsServicesMonitor: "thin-status-v1",
      salesPagesPolish: "package-positioning-v1",
      renderBuildFix: "no-sqlite-in-client-v1",
      setupIndependent: "integrations-one-panel-v1",
      bootTabsReady: "auth-only-v1",
      deploySmoke: "soft-pass-deploy-window-v3",
      faultsImprovements: "phases-2-6-v1",
      mailboxIcloud: "smtp-mail-me-v1",
      mailboxSendAs: "editable-from-v1",
      mailboxIcloudFix: "hydrate-dirty-v1",
      mailboxPersist: "verify-disk-v2",
      takeoffSkill: "drawing-first-v8-routes-page",
      takeoffMacScroll: "studio-rail-page-scroll-v1",
      takeoffAiConfirm: "pins-only-v2",
      takeoffBlakePipeRuns: "vector-stroke-v1",
      takeoffBlakeLearn: "habits-v1",
      takeoffBlakePropose: "routes-equipment-ai-v2",
      takeoffEleven: "sprint-7",
      takeoffHeatHarmony: "hd-send-v1",
      recurringServices: "upcoming-4w-v1",
      recurringGenerate: "server-v1",
      poStockReceive: "idempotent-v1",
    },
    daywork: {
      sheetCount: dayworkSheetCount,
      signedCount: dayworkSignedCount,
      lastWrite,
    },
    checkedAt: new Date().toISOString(),
  });
}
