/** NeXa Takeoff Studio — Togal-style classification + geometry model (NeXa / EWG, not a clone of Togal). */

import type { TakeoffConfidence, TakeoffMeasureMethod } from "@/lib/takeoff-skill";

export type StudioClassKind = "area" | "linear" | "count";

export type StudioTool =
  | "pan"
  | "select"
  | "count"
  | "linear"
  | "area"
  | "rect"
  | "scale"
  | "measure";

export type StudioPoint = { x: number; y: number };

export type StudioAiReviewStatus = "pending" | "confirmed" | "rejected";

export type StudioAiReviewMeasuredQuantity = {
  id: string;
  assemblyId?: string;
  kind: "primary" | "secondary";
  code: string;
  description: string;
  quantity?: number;
  unit: string;
  method?: TakeoffMeasureMethod;
  confidence?: TakeoffConfidence;
  sourceSheetIds?: string[];
  derivation?: string;
  notes?: string;
  tagMatches?: Array<{
    id: string;
    documentId: string;
    fileName?: string;
    pageNumber: number;
    text?: string;
    x: number;
    y: number;
    pageWidth?: number;
    pageHeight?: number;
    excluded?: boolean;
    manual?: boolean;
    derived?: boolean;
  }>;
};

/** Service layer — filter takeoff work like CAD layers (hot/cold vs heating vs waste). */
export type StudioServiceLayerId =
  | "hot-cold"
  | "heating"
  | "sanitary-waste"
  | "gas"
  | "general";

export type StudioClassification = {
  id: string;
  kind: StudioClassKind;
  name: string;
  colour: string;
  unit: "m2" | "m" | "nr";
  /** Service layer for filter / hide — optional for older projects. */
  layer?: StudioServiceLayerId;
  notes?: string;
};

export type StudioGeometry =
  | {
      id: string;
      classificationId: string;
      kind: "count";
      documentId: string;
      page: number;
      point: StudioPoint;
      source?: "manual" | "ai";
      confidence?: TakeoffConfidence;
      reviewStatus?: StudioAiReviewStatus;
      sourceTagId?: string;
      sourceText?: string;
      /** Auto fitting from a pipe run (elbow / coupling). */
      fittingKind?: "90-elbow" | "coupling";
      linkedLinearId?: string;
      material?: string;
      diameter?: string;
      autoGenerated?: boolean;
    }
  | {
      id: string;
      classificationId: string;
      kind: "linear";
      documentId: string;
      page: number;
      points: StudioPoint[];
      closed?: boolean;
      source?: "manual" | "ai";
      confidence?: TakeoffConfidence;
      reviewStatus?: StudioAiReviewStatus;
      notes?: string;
      /** Pipe stock size — drives auto elbows / couplings. */
      material?: string;
      diameter?: string;
      stockLengthM?: number;
      pipeSpecId?: string;
    }
  | {
      id: string;
      classificationId: string;
      kind: "area";
      documentId: string;
      page: number;
      points: StudioPoint[];
      closed: boolean;
      source?: "manual" | "ai";
    };

export type StudioPageScale = {
  documentId: string;
  page: number;
  /** Metres per PDF page-unit (same space as pdf.js viewport at scale 1). */
  metresPerUnit: number;
  /** Optional two-point calibration used to derive metresPerUnit. */
  calibrateFrom?: StudioPoint;
  calibrateTo?: StudioPoint;
  knownMetres?: number;
  /** e.g. "1:50" when applied from a sheet ratio hint. */
  label?: string;
};

export type StudioState = {
  version: 1;
  activeDocumentId?: string;
  activePage: number;
  activeClassificationId?: string;
  /** Filter geometries / class list by service layer (`all` = show everything). */
  activeLayerId?: StudioServiceLayerId | "all";
  /** Active pipe size for Length tool (e.g. cu-22). */
  activePipeSpecId?: string;
  tool: StudioTool;
  classifications: StudioClassification[];
  geometries: StudioGeometry[];
  scales: StudioPageScale[];
  aiReviewStatus?: StudioAiReviewStatus;
  aiReviewMeasured?: StudioAiReviewMeasuredQuantity[];
  aiReviewUpdatedAt?: string;
  updatedAt: string;
};

const COLOURS = ["#1998cf", "#2e8c7d", "#c45c26", "#7a4f9a", "#b43a3a", "#b36a16", "#14618c", "#5b6b7a"];

export const STUDIO_SERVICE_LAYERS: Array<{ id: StudioServiceLayerId | "all"; label: string }> = [
  { id: "all", label: "Master / all" },
  { id: "hot-cold", label: "Hot & cold" },
  { id: "heating", label: "Heating" },
  { id: "sanitary-waste", label: "Sanitary & waste" },
  { id: "gas", label: "Gas" },
  { id: "general", label: "General" },
];

/** Preset pipe / fixture services with fixed colours — tap these instead of guessing. */
export const SERVICE_CLASS_DEFS: Array<StudioClassification & { role?: "hot" | "cold" | "waste" }> = [
  { id: "cls-ai-P-PIPE-H", kind: "linear", name: "Hot pipe runs", colour: "#d64545", unit: "m", layer: "hot-cold", role: "hot", notes: "Domestic hot water" },
  { id: "cls-ai-P-PIPE-C", kind: "linear", name: "Cold pipe runs", colour: "#2878c8", unit: "m", layer: "hot-cold", role: "cold", notes: "Domestic cold water" },
  { id: "cls-linear-heating-flow", kind: "linear", name: "Heating flow", colour: "#f97316", unit: "m", layer: "heating", notes: "CH flow" },
  { id: "cls-linear-heating-return", kind: "linear", name: "Heating return", colour: "#7c3aed", unit: "m", layer: "heating", notes: "CH return" },
  { id: "cls-linear-ufh", kind: "linear", name: "UFH loops", colour: "#2ea66f", unit: "m", layer: "heating", notes: "Underfloor heating" },
  { id: "cls-ai-P-WASTE", kind: "linear", name: "Waste / soil runs", colour: "#8a5a32", unit: "m", layer: "sanitary-waste", role: "waste", notes: "Waste and soil" },
  { id: "cls-count-sanitary", kind: "count", name: "Sanitary ware", colour: "#7a4f9a", unit: "nr", layer: "sanitary-waste", notes: "WC, WHB, bath, shower" },
  { id: "cls-linear-gas", kind: "linear", name: "Gas pipe runs", colour: "#d2a400", unit: "m", layer: "gas", notes: "Gas pipework" },
];

const PIPE_CLASS_DEFS = SERVICE_CLASS_DEFS.filter((def) => def.role === "hot" || def.role === "cold" || def.role === "waste") as Array<{
  id: string;
  kind: "linear";
  name: string;
  colour: string;
  unit: "m";
  layer: StudioServiceLayerId;
  role: "hot" | "cold" | "waste";
  notes?: string;
}>;

export function createDefaultStudioState(): StudioState {
  const stamp = new Date().toISOString();
  const classifications: StudioClassification[] = [
    { id: "cls-area-rooms", kind: "area", name: "Rooms", colour: COLOURS[0] || "#1998cf", unit: "m2", layer: "general" },
    { id: "cls-linear-walls", kind: "linear", name: "Walls", colour: COLOURS[1] || "#2e8c7d", unit: "m", layer: "general" },
    { id: "cls-count-doors", kind: "count", name: "Doors", colour: COLOURS[2] || "#c45c26", unit: "nr", layer: "general" },
    ...SERVICE_CLASS_DEFS.map(({ role: _role, ...cls }) => cls),
  ];
  const cold = classifications.find((cls) => cls.id === "cls-ai-P-PIPE-C");
  return {
    version: 1,
    activePage: 1,
    tool: "pan",
    activeLayerId: "all",
    activeClassificationId: cold?.id || classifications[0]?.id,
    classifications,
    geometries: [],
    scales: [],
    updatedAt: stamp,
  };
}

export function detectScaleRatioHints(text: string): string[] {
  const hints = new Set<string>();
  const patterns = [
    /\bSCALE\s*[:=]?\s*1\s*[:/]\s*(\d+)\b/gi,
    /\b1\s*:\s*(\d+)\b/g,
    /\b1\s*\/\s*(\d+)\b/g,
  ];
  for (const pattern of patterns) {
    for (const match of text.matchAll(pattern)) {
      const denom = Number(match[1]);
      if (denom >= 10 && denom <= 5000) hints.add(`1:${denom}`);
    }
  }
  return [...hints].slice(0, 4);
}

/**
 * Convert a printed ratio (e.g. 1:100) into metres-per-canvas-unit.
 * Assumes PDF user units are points (1/72"), then divides by the canvas render scale.
 */
export function metresPerUnitFromRatio(denom: number, renderScale = 1.35): number | null {
  if (!(denom > 0) || !(renderScale > 0)) return null;
  const metresPerPdfPoint = (1 / 72) * 0.0254 * denom;
  return metresPerPdfPoint / renderScale;
}

export function parseScaleRatioLabel(label: string): number | null {
  const match = /^1\s*[:/]\s*(\d+)$/i.exec(label.trim());
  if (!match) return null;
  const denom = Number(match[1]);
  return denom >= 10 && denom <= 5000 ? denom : null;
}

export function studioId(prefix: string) {
  return `${prefix}-${Date.now().toString(36)}-${Math.random().toString(36).slice(2, 7)}`;
}

export function nextClassificationColour(existing: StudioClassification[]) {
  return COLOURS[existing.length % COLOURS.length] || COLOURS[0] || "#1998cf";
}

export function polylineLength(points: StudioPoint[]): number {
  let total = 0;
  for (let i = 1; i < points.length; i += 1) {
    const a = points[i - 1];
    const b = points[i];
    if (!a || !b) continue;
    total += Math.hypot(b.x - a.x, b.y - a.y);
  }
  return total;
}

/** Shoelace area in page units². */
export function polygonArea(points: StudioPoint[]): number {
  if (points.length < 3) return 0;
  let sum = 0;
  for (let i = 0; i < points.length; i += 1) {
    const a = points[i];
    const b = points[(i + 1) % points.length];
    if (!a || !b) continue;
    sum += a.x * b.y - b.x * a.y;
  }
  return Math.abs(sum) / 2;
}

export function scaleForPage(studio: StudioState, documentId: string, page: number): StudioPageScale | undefined {
  return studio.scales.find((row) => row.documentId === documentId && row.page === page);
}

export function isAiStudioGeometry(geo: StudioGeometry): boolean {
  // Explicit manual accept/edit wins over ai-* id prefixes from Blake/vision.
  if (geo.source === "manual") return false;
  return geo.source === "ai" || geo.id.startsWith("ai-");
}

export function studioHasAiCounts(studio: StudioState): boolean {
  return studio.geometries.some((geo) => geo.kind === "count" && isAiStudioGeometry(geo))
    || Boolean(studio.aiReviewMeasured?.some((row) =>
      (row.tagMatches || []).some((match) => !match.excluded),
    ));
}

export function studioHasAiPipeRuns(studio: StudioState): boolean {
  return studio.geometries.some((geo) => geo.kind === "linear" && isAiStudioGeometry(geo));
}

/** Ensure preset coloured pipe/service classes exist (Hot/Cold/Heating/Waste…). Does not overwrite user colour edits. */
export function ensureServiceClassifications(studio: StudioState): StudioState {
  const classifications = [...studio.classifications];
  let changed = false;
  for (const def of SERVICE_CLASS_DEFS) {
    const idx = classifications.findIndex((cls) => cls.id === def.id);
    if (idx < 0) {
      const { role: _role, ...cls } = def;
      classifications.push(cls);
      changed = true;
      continue;
    }
    const existing = classifications[idx]!;
    let next = existing;
    // Backfill layer on older projects without changing colour the user may have edited.
    if (!existing.layer && def.layer) {
      next = { ...next, layer: def.layer };
    }
    // Migrate Blake's old green "cold" swatch to standard plumbing blue (only exact prior default).
    if (def.id === "cls-ai-P-PIPE-C" && existing.colour.toLowerCase() === "#1f8f5f") {
      next = { ...next, colour: def.colour };
    }
    if (next !== existing) {
      classifications[idx] = next;
      changed = true;
    }
  }
  if (!changed) return studio;
  return { ...studio, classifications, updatedAt: new Date().toISOString() };
}

/** @deprecated alias — Blake pipe import path */
export function ensurePipeRunClassifications(studio: StudioState): StudioState {
  return ensureServiceClassifications(studio);
}

export function classificationLayer(cls: StudioClassification): StudioServiceLayerId {
  return cls.layer || "general";
}

export function setStudioActiveLayer(
  studio: StudioState,
  layerId: StudioServiceLayerId | "all",
): StudioState {
  const next = ensureServiceClassifications(studio);
  if (layerId === "all") {
    return { ...next, activeLayerId: "all", updatedAt: new Date().toISOString() };
  }
  const inLayer = next.classifications.filter((cls) => classificationLayer(cls) === layerId);
  const keepActive = inLayer.some((cls) => cls.id === next.activeClassificationId);
  const preferred =
    inLayer.find((cls) => cls.kind === "linear")
    || inLayer[0]
    || next.classifications.find((cls) => cls.id === next.activeClassificationId);
  return {
    ...next,
    activeLayerId: layerId,
    activeClassificationId: keepActive ? next.activeClassificationId : preferred?.id,
    tool: preferred?.kind || next.tool,
    updatedAt: new Date().toISOString(),
  };
}

export function setClassificationColour(
  studio: StudioState,
  classificationId: string,
  colour: string,
): StudioState {
  const nextColour = /^#?[0-9a-fA-F]{6}$/.test(colour.trim())
    ? (colour.startsWith("#") ? colour : `#${colour}`)
    : null;
  if (!nextColour) return studio;
  return {
    ...studio,
    classifications: studio.classifications.map((cls) =>
      cls.id === classificationId ? { ...cls, colour: nextColour } : cls,
    ),
    updatedAt: new Date().toISOString(),
  };
}

/** Apply the first scale ratio hint found in drawing text to every page that lacks a scale. */
export function applyScaleHintsToStudio(
  studio: StudioState,
  pages: Array<{ documentId: string; pageNumber: number; fullText?: string }>,
  renderScale = 1.35,
): { studio: StudioState; appliedLabel: string | null } {
  let appliedLabel: string | null = null;
  let metresPerUnit: number | null = null;
  for (const page of pages) {
    const hints = detectScaleRatioHints(page.fullText || "");
    if (!hints[0]) continue;
    const denom = parseScaleRatioLabel(hints[0]);
    if (!denom) continue;
    metresPerUnit = metresPerUnitFromRatio(denom, renderScale);
    appliedLabel = hints[0];
    break;
  }
  if (!metresPerUnit || !appliedLabel) return { studio, appliedLabel: null };

  const scales = [...studio.scales];
  for (const page of pages) {
    const exists = scales.some((row) => row.documentId === page.documentId && row.page === page.pageNumber);
    if (exists) continue;
    scales.push({
      documentId: page.documentId,
      page: page.pageNumber,
      metresPerUnit,
      label: appliedLabel,
    });
  }
  return {
    studio: { ...studio, scales, updatedAt: new Date().toISOString() },
    appliedLabel,
  };
}

export function importPipeRunsIntoStudio(
  studio: StudioState,
  runs: Array<{
    documentId: string;
    pageNumber: number;
    points: StudioPoint[];
    role: "hot" | "cold" | "waste" | "other";
    pageHeight: number;
    colourHex?: string;
  }>,
  options?: {
    renderScale?: number;
    replaceExistingAiPipes?: boolean;
    aiReviewStatus?: StudioAiReviewStatus;
    /** Size Blake runs (e.g. cu-22) so BOQ + fittings resolve. */
    pipeSpec?: { id: string; material: string; diameter: string; stockLengthM: number };
    wastePipeSpec?: { id: string; material: string; diameter: string; stockLengthM: number };
  },
): StudioState {
  const renderScale = options?.renderScale ?? 1.35;
  let next = ensurePipeRunClassifications(studio);
  let keep = next.geometries;
  if (options?.replaceExistingAiPipes) {
    // Only wipe measured Blake pipes (ai-pipe-*), never design-propose stubs (ai-propose-*).
    const removedPipeIds = new Set(
      next.geometries
        .filter((geo) => geo.kind === "linear" && geo.id.startsWith("ai-pipe-"))
        .map((geo) => geo.id),
    );
    keep = next.geometries.filter((geo) => {
      if (geo.kind === "linear" && geo.id.startsWith("ai-pipe-")) return false;
      if (
        geo.kind === "count"
        && geo.autoGenerated
        && geo.linkedLinearId
        && removedPipeIds.has(geo.linkedLinearId)
      ) {
        return false;
      }
      return true;
    });
  }
  const geometries = [...keep];

  for (const [index, run] of runs.entries()) {
    if (run.role === "other" || run.points.length < 2) continue;
    const def = PIPE_CLASS_DEFS.find((row) => row.role === run.role);
    if (!def) continue;
    const points = run.points.map((point) => ({
      x: point.x * renderScale,
      y: (run.pageHeight - point.y) * renderScale,
    }));
    const sized = run.role === "waste" ? options?.wastePipeSpec : options?.pipeSpec;
    geometries.push({
      id: `ai-pipe-${run.documentId}-${run.pageNumber}-${index}`,
      classificationId: def.id,
      kind: "linear",
      documentId: run.documentId,
      page: run.pageNumber,
      points,
      source: "ai",
      confidence: "Medium",
      reviewStatus: options?.aiReviewStatus ?? "pending",
      notes: `Blake vector stroke · ${run.colourHex || run.role}`,
      material: sized?.material,
      diameter: sized?.diameter,
      stockLengthM: sized?.stockLengthM,
      pipeSpecId: sized?.id,
    });
  }

  const firstPipe = geometries.find((geo) => geo.kind === "linear" && isAiStudioGeometry(geo));
  return {
    ...next,
    geometries,
    activeDocumentId: firstPipe?.documentId || next.activeDocumentId,
    activePage: firstPipe?.page || next.activePage,
    activeClassificationId: firstPipe?.classificationId || next.activeClassificationId,
    tool: firstPipe ? "select" : next.tool,
    updatedAt: new Date().toISOString(),
  };
}

/** Hard review gate — only real AI count pins block Core push. Pipe runs live on the sheet/BOQ. */
export function studioNeedsAiReview(studio: StudioState): boolean {
  return studio.aiReviewStatus === "pending" && studioHasAiCounts(studio);
}

export function countAiStudioPipeRuns(studio: StudioState): number {
  return studio.geometries.filter((geo) => geo.kind === "linear" && isAiStudioGeometry(geo)).length;
}

export function countAiStudioCountPins(studio: StudioState): number {
  return studio.geometries.filter((geo) => geo.kind === "count" && isAiStudioGeometry(geo) && !geo.autoGenerated).length;
}

export type StudioQuantityRow = {
  classificationId: string;
  name: string;
  kind: StudioClassKind;
  colour: string;
  quantity: number;
  unit: string;
  pieces: number;
};

export function summariseStudioQuantities(studio: StudioState): StudioQuantityRow[] {
  return studio.classifications.map((cls) => {
    const items = studio.geometries.filter((geo) => geo.classificationId === cls.id);
    let quantity = 0;
    for (const geo of items) {
      const scale = scaleForPage(studio, geo.documentId, geo.page);
      const mpu = scale?.metresPerUnit || 0;
      if (geo.kind === "count") {
        quantity += 1;
      } else if (geo.kind === "linear") {
        quantity += polylineLength(geo.points) * mpu;
      } else if (geo.kind === "area" && geo.closed) {
        quantity += polygonArea(geo.points) * mpu * mpu;
      }
    }
    return {
      classificationId: cls.id,
      name: cls.name,
      kind: cls.kind,
      colour: cls.colour,
      quantity: cls.kind === "count" ? quantity : Number(quantity.toFixed(2)),
      unit: cls.unit,
      pieces: items.length,
    };
  });
}

export function studioQuantitiesToMaterialAllowances(
  studio: StudioState,
  projectId: string,
): Array<{
  id: string;
  section: string;
  description: string;
  quantity: number;
  unit: string;
  unitCost: number;
  markupPercent: number;
  supplierRequired: boolean;
}> {
  const sizedLinearIds = new Set(
    studio.geometries
      .filter((geo) => geo.kind === "linear" && (geo.material || geo.diameter))
      .map((geo) => geo.classificationId),
  );
  const fittingClassIds = new Set(["cls-fit-90-elbow", "cls-fit-coupling"]);
  return summariseStudioQuantities(studio)
    .filter((row) => row.quantity > 0)
    .filter((row) => !sizedLinearIds.has(row.classificationId) && !fittingClassIds.has(row.classificationId))
    .map((row) => ({
      id: `studio-mat-${projectId}-${row.classificationId}`,
      section: row.kind === "area" ? "Areas" : row.kind === "linear" ? "Linears" : "Counts",
      description: `Takeoff · ${row.name}`,
      quantity: row.quantity,
      unit: row.unit,
      unitCost: 0,
      markupPercent: 0,
      supplierRequired: false,
    }));
}

/** Import skill text-tag count pins onto the Studio canvas as Count classifications. */
export function importSkillCountsIntoStudio(
  studio: StudioState,
  measured: Array<{
    id: string;
    assemblyId?: string;
    kind: "primary" | "secondary";
    code: string;
    description: string;
    quantity?: number;
    unit: string;
    method?: string;
    confidence?: TakeoffConfidence;
    sourceSheetIds?: string[];
    tagMatches?: Array<{
      id: string;
      documentId: string;
      fileName?: string;
      pageNumber: number;
      text?: string;
      x: number;
      y: number;
      pageWidth?: number;
      pageHeight?: number;
      excluded?: boolean;
      manual?: boolean;
      derived?: boolean;
    }>;
  }>,
  options?: {
    canvasWidth?: number;
    canvasHeight?: number;
    replaceExistingAi?: boolean;
    aiReviewStatus?: StudioAiReviewStatus;
  },
): StudioState {
  const canvasW = options?.canvasWidth || 0;
  // Only replace measured AI count pins — keep pipe runs, fittings, and propose-* plant pins.
  const keep = options?.replaceExistingAi
    ? studio.geometries.filter((geo) => {
      if (geo.kind !== "count" || geo.autoGenerated) return true;
      if (!isAiStudioGeometry(geo)) return true;
      if (geo.id.startsWith("ai-propose-")) return true;
      return false;
    })
    : studio.geometries;

  const classifications = [...studio.classifications];
  const geometries = [...keep];

  for (const row of measured) {
    if (row.kind !== "primary" || row.unit !== "nr") continue;
    const matches = (row.tagMatches || []).filter((match) => !match.excluded);
    if (!matches.length) continue;

    let cls = classifications.find((item) => item.id === `cls-ai-${row.code}`);
    if (!cls) {
      cls = {
        id: `cls-ai-${row.code}`,
        kind: "count",
        name: row.description || row.code,
        colour: nextClassificationColour(classifications),
        unit: "nr",
        notes: `Imported from Blake · ${row.code}`,
      };
      classifications.push(cls);
    }

    for (const match of matches) {
      const pageHeight = match.pageHeight || 0;
      const renderScale =
        canvasW && match.pageWidth ? canvasW / match.pageWidth : 1.35;
      // PDF text transforms are origin bottom-left; Studio canvas is top-left at render scale.
      geometries.push({
        id: `ai-${match.id}`,
        classificationId: cls.id,
        kind: "count",
        documentId: match.documentId,
        page: match.pageNumber || 1,
        source: "ai",
        confidence: row.confidence,
        reviewStatus: options?.aiReviewStatus ?? studio.aiReviewStatus ?? "pending",
        sourceTagId: match.id,
        sourceText: match.text,
        point: {
          x: match.x * renderScale,
          y: pageHeight ? (pageHeight - match.y) * renderScale : match.y * renderScale,
        },
      });
    }
  }

  const firstAi = geometries.find((geo) => geo.id.startsWith("ai-"));
  const firstAiClass = classifications.find((c) => c.id.startsWith("cls-ai-"));

  return {
    ...studio,
    classifications,
    geometries,
    activeDocumentId: firstAi?.documentId || studio.activeDocumentId,
    activePage: firstAi?.page || studio.activePage,
    activeClassificationId: firstAiClass?.id || studio.activeClassificationId,
    tool: "select",
    aiReviewStatus: options?.aiReviewStatus ?? studio.aiReviewStatus,
    aiReviewMeasured: studio.aiReviewMeasured,
    aiReviewUpdatedAt: studio.aiReviewUpdatedAt,
    updatedAt: new Date().toISOString(),
  };
}
