/** NeXa Takeoff Studio — Togal-style classification + geometry model (NeXa / EWG, not a clone of Togal). */

import type { TakeoffConfidence, TakeoffMeasureMethod } from "@/lib/takeoff-skill";

export type StudioClassKind = "area" | "linear" | "count";

export type StudioTool =
  | "pan"
  | "select"
  | "count"
  | "linear"
  | "area"
  | "rect"
  | "scale"
  | "measure";

export type StudioPoint = { x: number; y: number };

export type StudioAiReviewStatus = "pending" | "confirmed" | "rejected";

export type StudioAiReviewMeasuredQuantity = {
  id: string;
  assemblyId?: string;
  kind: "primary" | "secondary";
  code: string;
  description: string;
  quantity?: number;
  unit: string;
  method?: TakeoffMeasureMethod;
  confidence?: TakeoffConfidence;
  sourceSheetIds?: string[];
  derivation?: string;
  notes?: string;
  tagMatches?: Array<{
    id: string;
    documentId: string;
    fileName?: string;
    pageNumber: number;
    text?: string;
    x: number;
    y: number;
    pageWidth?: number;
    pageHeight?: number;
    excluded?: boolean;
    manual?: boolean;
    derived?: boolean;
  }>;
};

/** Builtin service layers — custom layers use ids like `custom-…`. */
export type StudioBuiltinLayerId =
  | "hot-cold"
  | "heating"
  | "sanitary-waste"
  | "gas"
  | "general";

/** Service layer — filter takeoff work like CAD layers (hot/cold vs heating vs waste). */
export type StudioServiceLayerId = StudioBuiltinLayerId | string;

export type StudioCustomLayer = {
  id: string;
  label: string;
};

/** Collapsible Draw-as groups inside a service layer (Valves, Boilers, …). */
export type StudioClassGroupId =
  | "pipe-runs"
  | "valves"
  | "fittings"
  | "radiators-valves"
  | "ufh-manifolds"
  | "ancillaries"
  | "boilers-plant"
  | "sanitary-ware"
  | "traps-waste"
  | "cocks-meters"
  | "general";

export const STUDIO_CLASS_GROUPS: Array<{ id: StudioClassGroupId; label: string }> = [
  { id: "pipe-runs", label: "Pipe runs" },
  { id: "valves", label: "Valves" },
  { id: "fittings", label: "Fittings" },
  { id: "radiators-valves", label: "Radiators & valves" },
  { id: "ufh-manifolds", label: "UFH / manifolds" },
  { id: "ancillaries", label: "Ancillaries" },
  { id: "boilers-plant", label: "Boilers / plant" },
  { id: "sanitary-ware", label: "Sanitary ware" },
  { id: "traps-waste", label: "Traps & waste" },
  { id: "cocks-meters", label: "Cocks & meters" },
  { id: "general", label: "General" },
];

export function studioClassGroupLabel(groupId: StudioClassGroupId | string | undefined): string {
  const id = (groupId || "general") as StudioClassGroupId;
  return STUDIO_CLASS_GROUPS.find((row) => row.id === id)?.label || "General";
}

export type StudioClassification = {
  id: string;
  kind: StudioClassKind;
  name: string;
  colour: string;
  unit: "m2" | "m" | "nr";
  /** Service layer for filter / hide — optional for older projects. */
  layer?: StudioServiceLayerId;
  /** Collapsible Draw-as group within the layer — optional for older projects. */
  group?: StudioClassGroupId;
  notes?: string;
};

export type StudioGeometry =
  | {
      id: string;
      classificationId: string;
      kind: "count";
      documentId: string;
      page: number;
      point: StudioPoint;
      source?: "manual" | "ai";
      confidence?: TakeoffConfidence;
      reviewStatus?: StudioAiReviewStatus;
      sourceTagId?: string;
      sourceText?: string;
      /** Auto fitting from a pipe run (elbow / coupling). */
      fittingKind?: "90-elbow" | "coupling";
      linkedLinearId?: string;
      material?: string;
      diameter?: string;
      autoGenerated?: boolean;
    }
  | {
      id: string;
      classificationId: string;
      kind: "linear";
      documentId: string;
      page: number;
      points: StudioPoint[];
      closed?: boolean;
      source?: "manual" | "ai";
      confidence?: TakeoffConfidence;
      reviewStatus?: StudioAiReviewStatus;
      notes?: string;
      /** Pipe stock size — drives auto elbows / couplings. */
      material?: string;
      diameter?: string;
      stockLengthM?: number;
      pipeSpecId?: string;
      /**
       * Vertical extra metres — not drawn in 2D.
       * Prefer dropCount × dropHeightM when count > 0; otherwise riseDropM is a total override.
       * BoQ pipe m = plan length × scale + vertical (clamped ≥ 0).
       * Legacy projects may only have riseDropM (treated as 1 × height on resolve).
       */
      riseDropM?: number;
      /** Number of wall/ceiling drops on this run (integer ≥ 0). */
      dropCount?: number;
      /** Height of each drop in metres (e.g. 2.4). */
      dropHeightM?: number;
    }
  | {
      id: string;
      classificationId: string;
      kind: "area";
      documentId: string;
      page: number;
      points: StudioPoint[];
      closed: boolean;
      source?: "manual" | "ai";
    };

export type StudioPageScale = {
  documentId: string;
  page: number;
  /** Metres per PDF page-unit (same space as pdf.js viewport at scale 1). */
  metresPerUnit: number;
  /** Optional two-point calibration used to derive metresPerUnit. */
  calibrateFrom?: StudioPoint;
  calibrateTo?: StudioPoint;
  knownMetres?: number;
  /** e.g. "1:50" when applied from a sheet ratio hint. */
  label?: string;
};

export type StudioState = {
  version: 1;
  activeDocumentId?: string;
  activePage: number;
  activeClassificationId?: string;
  /** Filter geometries / class list by service layer (`all` = show everything). */
  activeLayerId?: StudioServiceLayerId | "all";
  /** Extra user-defined service layers (Ventilation, Fire alarm, …). */
  customLayers?: StudioCustomLayer[];
  /** Active pipe size for Length tool (e.g. cu-22). */
  activePipeSpecId?: string;
  tool: StudioTool;
  classifications: StudioClassification[];
  geometries: StudioGeometry[];
  scales: StudioPageScale[];
  aiReviewStatus?: StudioAiReviewStatus;
  aiReviewMeasured?: StudioAiReviewMeasuredQuantity[];
  aiReviewUpdatedAt?: string;
  updatedAt: string;
};

const COLOURS = ["#1998cf", "#2e8c7d", "#c45c26", "#7a4f9a", "#b43a3a", "#b36a16", "#14618c", "#5b6b7a"];

export const STUDIO_SERVICE_LAYERS: Array<{ id: StudioServiceLayerId | "all"; label: string }> = [
  { id: "all", label: "Master / all" },
  { id: "hot-cold", label: "Hot & cold" },
  { id: "heating", label: "Heating" },
  { id: "sanitary-waste", label: "Sanitary & waste" },
  { id: "gas", label: "Gas" },
  { id: "general", label: "General" },
];

/** Builtin + custom layers for filters / BOQ tabs. */
export function listStudioLayers(studio: StudioState): Array<{ id: StudioServiceLayerId | "all"; label: string }> {
  const custom = (studio.customLayers || []).map((row) => ({
    id: row.id,
    label: row.label,
  }));
  return [...STUDIO_SERVICE_LAYERS, ...custom];
}

export function addCustomStudioLayer(studio: StudioState, label: string): StudioState {
  const name = label.trim();
  if (!name) return studio;
  const existing = (studio.customLayers || []).some(
    (row) => row.label.toLowerCase() === name.toLowerCase(),
  );
  if (existing) return studio;
  const id = studioId("custom");
  return {
    ...studio,
    customLayers: [...(studio.customLayers || []), { id, label: name }],
    activeLayerId: id,
    updatedAt: new Date().toISOString(),
  };
}

export function removeCustomStudioLayer(studio: StudioState, layerId: string): StudioState {
  if (!layerId.startsWith("custom-") && !(studio.customLayers || []).some((row) => row.id === layerId)) {
    return studio;
  }
  const customLayers = (studio.customLayers || []).filter((row) => row.id !== layerId);
  const classifications = studio.classifications.map((cls) =>
    cls.layer === layerId ? { ...cls, layer: "general" as StudioServiceLayerId } : cls,
  );
  return {
    ...studio,
    customLayers,
    classifications,
    activeLayerId: studio.activeLayerId === layerId ? "all" : studio.activeLayerId,
    updatedAt: new Date().toISOString(),
  };
}

/** Preset pipe / fixture services with fixed colours — tap these instead of guessing. */
export const SERVICE_CLASS_DEFS: Array<StudioClassification & { role?: "hot" | "cold" | "waste" }> = [
  // Hot & cold — pipe runs, then valves / fittings in collapsible Draw-as groups
  { id: "cls-ai-P-PIPE-H", kind: "linear", name: "Hot pipe runs", colour: "#d64545", unit: "m", layer: "hot-cold", group: "pipe-runs", role: "hot", notes: "Domestic hot water" },
  { id: "cls-ai-P-PIPE-C", kind: "linear", name: "Cold pipe runs", colour: "#2878c8", unit: "m", layer: "hot-cold", group: "pipe-runs", role: "cold", notes: "Domestic cold water" },
  { id: "cls-count-isolation-valve", kind: "count", name: "Isolation valve", colour: "#bf4f14", unit: "nr", layer: "hot-cold", group: "valves", notes: "Service / isolator" },
  { id: "cls-count-check-valve", kind: "count", name: "Check valve (NRV)", colour: "#c2410c", unit: "nr", layer: "hot-cold", group: "valves", notes: "Non-return valve" },
  { id: "cls-count-double-check", kind: "count", name: "Double check valve", colour: "#9a3412", unit: "nr", layer: "hot-cold", group: "valves", notes: "Backflow prevention" },
  { id: "cls-count-prv", kind: "count", name: "PRV", colour: "#a16207", unit: "nr", layer: "hot-cold", group: "valves", notes: "Pressure reducing valve" },
  { id: "cls-count-stopcock", kind: "count", name: "Stopcock", colour: "#854d0e", unit: "nr", layer: "hot-cold", group: "valves", notes: "Stop valve / stoptap" },
  { id: "cls-count-ball-valve", kind: "count", name: "Ball valve", colour: "#b45309", unit: "nr", layer: "hot-cold", group: "valves", notes: "Full-bore ball valve" },
  { id: "cls-count-gate-valve", kind: "count", name: "Gate valve", colour: "#92400e", unit: "nr", layer: "hot-cold", group: "valves", notes: "Gate valve" },
  { id: "cls-count-tmv", kind: "count", name: "TMV", colour: "#dc2626", unit: "nr", layer: "hot-cold", group: "valves", notes: "Thermostatic mixing valve" },
  { id: "cls-count-flexi", kind: "count", name: "Flexi connector", colour: "#ea580c", unit: "nr", layer: "hot-cold", group: "fittings", notes: "Braided flexi hose / tail" },
  { id: "cls-count-exp-vessel-dhw", kind: "count", name: "Expansion vessel (DHW)", colour: "#1d4ed8", unit: "nr", layer: "hot-cold", group: "fittings", notes: "Unvented / DHW expansion" },
  { id: "cls-count-booster-pump", kind: "count", name: "Booster / secondary pump", colour: "#0369a1", unit: "nr", layer: "hot-cold", group: "fittings", notes: "Cold boost or secondary return pump" },

  // Heating — linears then valves / CH ancillaries (plant pins live in PLANT_CLASS_DEFS)
  { id: "cls-linear-heating-flow", kind: "linear", name: "Heating flow", colour: "#f97316", unit: "m", layer: "heating", group: "pipe-runs", notes: "CH flow" },
  { id: "cls-linear-heating-return", kind: "linear", name: "Heating return", colour: "#7c3aed", unit: "m", layer: "heating", group: "pipe-runs", notes: "CH return" },
  { id: "cls-linear-ufh", kind: "linear", name: "UFH loops", colour: "#2ea66f", unit: "m", layer: "heating", group: "pipe-runs", notes: "Underfloor heating" },
  { id: "cls-count-trv", kind: "count", name: "TRV", colour: "#ea580c", unit: "nr", layer: "heating", group: "radiators-valves", notes: "Thermostatic radiator valve" },
  { id: "cls-count-lockshield", kind: "count", name: "Lockshield", colour: "#c2410c", unit: "nr", layer: "heating", group: "radiators-valves", notes: "Lockshield radiator valve" },
  { id: "cls-count-zone-valve", kind: "count", name: "Zone / motorised valve", colour: "#7c3aed", unit: "nr", layer: "heating", group: "radiators-valves", notes: "2-port / 3-port motorised" },
  { id: "cls-count-auto-air-vent", kind: "count", name: "Auto air vent", colour: "#0891b2", unit: "nr", layer: "heating", group: "ancillaries", notes: "Automatic air vent" },
  { id: "cls-count-mag-filter", kind: "count", name: "Magnetic filter", colour: "#475569", unit: "nr", layer: "heating", group: "ancillaries", notes: "MagnaClean / system filter" },
  { id: "cls-count-filling-loop", kind: "count", name: "Filling loop", colour: "#64748b", unit: "nr", layer: "heating", group: "ancillaries", notes: "Temporary / permanent filling loop" },
  { id: "cls-count-pressure-gauge", kind: "count", name: "Pressure gauge", colour: "#57534e", unit: "nr", layer: "heating", group: "ancillaries", notes: "System pressure gauge" },
  { id: "cls-count-circ-pump", kind: "count", name: "Circulating pump", colour: "#0f766e", unit: "nr", layer: "heating", group: "ancillaries", notes: "CH circulating pump" },
  { id: "cls-count-manifold-actuator", kind: "count", name: "Manifold actuator", colour: "#7c3aed", unit: "nr", layer: "heating", group: "ufh-manifolds", notes: "UFH manifold actuator" },
  { id: "cls-count-exp-vessel-ch", kind: "count", name: "Expansion vessel (CH)", colour: "#1e40af", unit: "nr", layer: "heating", group: "ancillaries", notes: "Sealed system expansion vessel" },

  // Sanitary & waste
  { id: "cls-ai-P-WASTE", kind: "linear", name: "Waste / soil runs", colour: "#8a5a32", unit: "m", layer: "sanitary-waste", group: "pipe-runs", role: "waste", notes: "Waste and soil" },
  { id: "cls-count-sanitary", kind: "count", name: "Sanitary ware", colour: "#7a4f9a", unit: "nr", layer: "sanitary-waste", group: "sanitary-ware", notes: "Generic sanitary count" },
  { id: "cls-count-wc", kind: "count", name: "WC", colour: "#6d28d9", unit: "nr", layer: "sanitary-waste", group: "sanitary-ware", notes: "WC pan / toilet" },
  { id: "cls-count-whb", kind: "count", name: "WHB / basin", colour: "#7c3aed", unit: "nr", layer: "sanitary-waste", group: "sanitary-ware", notes: "Wash hand basin" },
  { id: "cls-count-bath", kind: "count", name: "Bath", colour: "#8b5cf6", unit: "nr", layer: "sanitary-waste", group: "sanitary-ware", notes: "Bath" },
  { id: "cls-count-shower", kind: "count", name: "Shower", colour: "#a855f7", unit: "nr", layer: "sanitary-waste", group: "sanitary-ware", notes: "Shower tray / enclosure" },
  { id: "cls-count-sink", kind: "count", name: "Sink", colour: "#9333ea", unit: "nr", layer: "sanitary-waste", group: "sanitary-ware", notes: "Kitchen / utility sink" },
  { id: "cls-count-bottle-trap", kind: "count", name: "Bottle trap", colour: "#78716c", unit: "nr", layer: "sanitary-waste", group: "traps-waste", notes: "Basin / sink bottle trap" },
  { id: "cls-count-gulley", kind: "count", name: "Gulley", colour: "#57534e", unit: "nr", layer: "sanitary-waste", group: "traps-waste", notes: "Yard / bottle gulley" },
  { id: "cls-count-aav", kind: "count", name: "Air admittance valve", colour: "#44403c", unit: "nr", layer: "sanitary-waste", group: "traps-waste", notes: "AAV / AVT" },
  { id: "cls-count-pan-connector", kind: "count", name: "WC pan connector", colour: "#a8a29e", unit: "nr", layer: "sanitary-waste", group: "traps-waste", notes: "Pan connector / WC connector" },
  { id: "cls-count-rodding-eye", kind: "count", name: "Rodding eye", colour: "#78716c", unit: "nr", layer: "sanitary-waste", group: "traps-waste", notes: "Access / rodding eye" },
  { id: "cls-count-soil-fitting", kind: "count", name: "Soil fitting", colour: "#57534e", unit: "nr", layer: "sanitary-waste", group: "traps-waste", notes: "Boss / branch / bend count" },

  // Gas
  { id: "cls-linear-gas", kind: "linear", name: "Gas pipe runs", colour: "#d2a400", unit: "m", layer: "gas", group: "pipe-runs", notes: "Gas pipework" },
  { id: "cls-count-gas-cock", kind: "count", name: "Gas cock", colour: "#ca8a04", unit: "nr", layer: "gas", group: "cocks-meters", notes: "Gas isolation / cock" },
  { id: "cls-count-gas-meter", kind: "count", name: "Gas meter", colour: "#a16207", unit: "nr", layer: "gas", group: "cocks-meters", notes: "Gas meter position" },
];

const PIPE_CLASS_DEFS = SERVICE_CLASS_DEFS.filter((def) => def.role === "hot" || def.role === "cold" || def.role === "waste") as Array<{
  id: string;
  kind: "linear";
  name: string;
  colour: string;
  unit: "m";
  layer: StudioServiceLayerId;
  role: "hot" | "cold" | "waste";
  notes?: string;
}>;

export function createDefaultStudioState(): StudioState {
  const stamp = new Date().toISOString();
  const classifications: StudioClassification[] = [
    { id: "cls-area-rooms", kind: "area", name: "Rooms", colour: COLOURS[0] || "#1998cf", unit: "m2", layer: "general", group: "general" },
    { id: "cls-linear-walls", kind: "linear", name: "Walls", colour: COLOURS[1] || "#2e8c7d", unit: "m", layer: "general", group: "general" },
    { id: "cls-count-doors", kind: "count", name: "Doors", colour: COLOURS[2] || "#c45c26", unit: "nr", layer: "general", group: "general" },
    ...SERVICE_CLASS_DEFS.map(({ role: _role, ...cls }) => cls),
  ];
  const cold = classifications.find((cls) => cls.id === "cls-ai-P-PIPE-C");
  return {
    version: 1,
    activePage: 1,
    tool: "pan",
    activeLayerId: "all",
    activeClassificationId: cold?.id || classifications[0]?.id,
    classifications,
    geometries: [],
    scales: [],
    updatedAt: stamp,
  };
}

export function detectScaleRatioHints(text: string): string[] {
  const hints = new Set<string>();
  const patterns = [
    /\bSCALE\s*[:=]?\s*1\s*[:/]\s*(\d+)\b/gi,
    /\b1\s*:\s*(\d+)\b/g,
    /\b1\s*\/\s*(\d+)\b/g,
  ];
  for (const pattern of patterns) {
    for (const match of text.matchAll(pattern)) {
      const denom = Number(match[1]);
      if (denom >= 10 && denom <= 5000) hints.add(`1:${denom}`);
    }
  }
  return [...hints].slice(0, 4);
}

/**
 * Convert a printed ratio (e.g. 1:100) into metres-per-canvas-unit.
 * Assumes PDF user units are points (1/72"), then divides by the canvas render scale.
 */
export function metresPerUnitFromRatio(denom: number, renderScale = 1.35): number | null {
  if (!(denom > 0) || !(renderScale > 0)) return null;
  const metresPerPdfPoint = (1 / 72) * 0.0254 * denom;
  return metresPerPdfPoint / renderScale;
}

export function parseScaleRatioLabel(label: string): number | null {
  const match = /^1\s*[:/]\s*(\d+)$/i.exec(label.trim());
  if (!match) return null;
  const denom = Number(match[1]);
  return denom >= 10 && denom <= 5000 ? denom : null;
}

export function studioId(prefix: string) {
  return `${prefix}-${Date.now().toString(36)}-${Math.random().toString(36).slice(2, 7)}`;
}

export function nextClassificationColour(existing: StudioClassification[]) {
  return COLOURS[existing.length % COLOURS.length] || COLOURS[0] || "#1998cf";
}

export function polylineLength(points: StudioPoint[]): number {
  let total = 0;
  for (let i = 1; i < points.length; i += 1) {
    const a = points[i - 1];
    const b = points[i];
    if (!a || !b) continue;
    total += Math.hypot(b.x - a.x, b.y - a.y);
  }
  return total;
}

/** Clamp vertical extra metres — never negative. */
export function clampRiseDropM(value?: number | null): number {
  if (value == null || !Number.isFinite(value)) return 0;
  return Math.max(0, value);
}

/** Clamp drop count to a non-negative integer. */
export function clampDropCount(value?: number | null): number {
  if (value == null || !Number.isFinite(value)) return 0;
  return Math.max(0, Math.floor(value));
}

export type LinearDropFields = {
  riseDropM?: number | null;
  dropCount?: number | null;
  dropHeightM?: number | null;
};

export type ResolvedLinearDrop = {
  /** Effective count for UI / elbows (legacy bare riseDropM → 1). */
  dropCount: number;
  /** Height per drop (legacy bare riseDropM → that total). */
  dropHeightM: number;
  /** Vertical metres added to plan length. */
  verticalM: number;
  /** Elbows at ceiling–wall junctions (one per drop). */
  elbowCount: number;
  /**
   * BoQ fragment without outer parens, e.g. `3 × 2.4 m drops` or `2.4 m drop`.
   * Empty when no vertical.
   */
  noteLabel: string;
  /** `drops` = N×H source of truth; `total` = riseDropM override; `none`. */
  mode: "drops" | "total" | "none";
};

function formatDropMetres(value: number): string {
  const rounded = Number(value.toFixed(1));
  return Number.isInteger(rounded) ? String(rounded) : String(rounded);
}

/** Keep N×H totals tidy (e.g. 3×2.4 → 7.2, not 7.199…'). */
export function roundDropMetres(value: number): number {
  return Math.round(value * 1000) / 1000;
}

/**
 * Resolve vertical metres for a Length run.
 * - dropCount > 0 → vertical = count × height (source of truth)
 * - dropCount === 0 with explicit count fields → riseDropM total override
 * - legacy only riseDropM → treat as 1 × height for display / elbows / metres
 */
export function resolveLinearDrop(fields: LinearDropFields): ResolvedLinearDrop {
  const hasCountFields = fields.dropCount != null || fields.dropHeightM != null;
  const count = clampDropCount(fields.dropCount);
  const height = clampRiseDropM(fields.dropHeightM);
  const total = clampRiseDropM(fields.riseDropM);

  if (hasCountFields) {
    if (count > 0) {
      const verticalM = roundDropMetres(count * height);
      if (!(verticalM > 0)) {
        return {
          dropCount: count,
          dropHeightM: height,
          verticalM: 0,
          elbowCount: 0,
          noteLabel: "",
          mode: "none",
        };
      }
      const noteLabel = count === 1
        ? `${formatDropMetres(height)} m drop`
        : `${count} × ${formatDropMetres(height)} m drops`;
      return {
        dropCount: count,
        dropHeightM: height,
        verticalM,
        elbowCount: count,
        noteLabel,
        mode: "drops",
      };
    }
    // count === 0 → optional total override
    if (total > 0) {
      return {
        dropCount: 0,
        dropHeightM: height,
        verticalM: total,
        elbowCount: 1,
        noteLabel: `${formatDropMetres(total)} m drop`,
        mode: "total",
      };
    }
    return {
      dropCount: 0,
      dropHeightM: height,
      verticalM: 0,
      elbowCount: 0,
      noteLabel: "",
      mode: "none",
    };
  }

  // Legacy: only riseDropM stored → migrate as 1 × height when loading/resolving
  if (total > 0) {
    return {
      dropCount: 1,
      dropHeightM: total,
      verticalM: total,
      elbowCount: 1,
      noteLabel: `${formatDropMetres(total)} m drop`,
      mode: "drops",
    };
  }
  return {
    dropCount: 0,
    dropHeightM: 0,
    verticalM: 0,
    elbowCount: 0,
    noteLabel: "",
    mode: "none",
  };
}

/** Normalise persisted fields: sync riseDropM; migrate bare riseDropM → count/height. */
export function syncLinearDropFields<T extends LinearDropFields>(fields: T): T & {
  dropCount: number;
  dropHeightM: number;
  riseDropM: number;
} {
  const resolved = resolveLinearDrop(fields);
  if (fields.dropCount != null || fields.dropHeightM != null) {
    const count = clampDropCount(fields.dropCount);
    const height = clampRiseDropM(fields.dropHeightM);
    const riseDropM = count > 0
      ? roundDropMetres(count * height)
      : clampRiseDropM(fields.riseDropM);
    return { ...fields, dropCount: count, dropHeightM: height, riseDropM };
  }
  // Migrate legacy
  if (resolved.verticalM > 0) {
    return {
      ...fields,
      dropCount: 1,
      dropHeightM: resolved.verticalM,
      riseDropM: resolved.verticalM,
    };
  }
  return { ...fields, dropCount: 0, dropHeightM: 0, riseDropM: 0 };
}

/**
 * Measured pipe metres for a Length run: plan polyline × scale + rise/drop.
 * Rise/drop alone still counts when scale is missing (absolute metres).
 */
export function linearMeasuredMetres(
  points: StudioPoint[],
  metresPerUnit: number,
  riseDropM?: number | null,
): number {
  const planM = metresPerUnit > 0 ? polylineLength(points) * metresPerUnit : 0;
  return Math.max(0, planM + clampRiseDropM(riseDropM));
}

/** Plan × scale + resolved vertical (count×height or total override / legacy). */
export function linearMeasuredMetresForGeo(
  points: StudioPoint[],
  metresPerUnit: number,
  fields: LinearDropFields,
): number {
  return linearMeasuredMetres(points, metresPerUnit, resolveLinearDrop(fields).verticalM);
}

/** Shoelace area in page units². */
export function polygonArea(points: StudioPoint[]): number {
  if (points.length < 3) return 0;
  let sum = 0;
  for (let i = 0; i < points.length; i += 1) {
    const a = points[i];
    const b = points[(i + 1) % points.length];
    if (!a || !b) continue;
    sum += a.x * b.y - b.x * a.y;
  }
  return Math.abs(sum) / 2;
}

export function scaleForPage(studio: StudioState, documentId: string, page: number): StudioPageScale | undefined {
  return studio.scales.find((row) => row.documentId === documentId && row.page === page);
}

/** Prefer existing calibrated scales; fill gaps from `incoming` without wiping user calibration. */
export function mergeStudioScales(
  preferred: StudioPageScale[],
  incoming: StudioPageScale[],
): StudioPageScale[] {
  const byKey = new Map<string, StudioPageScale>();
  const keyOf = (row: StudioPageScale) => `${row.documentId}::${row.page}`;
  for (const row of incoming) {
    if (!(row.metresPerUnit > 0)) continue;
    byKey.set(keyOf(row), row);
  }
  for (const row of preferred) {
    if (!(row.metresPerUnit > 0)) continue;
    const key = keyOf(row);
    const existing = byKey.get(key);
    // Prefer two-point / knownMetres user calibrations over sheet-ratio hints.
    if (!existing || row.knownMetres || row.calibrateFrom || !existing.knownMetres) {
      byKey.set(key, row);
    }
  }
  return [...byKey.values()];
}

/**
 * When a drawing has scale on one page, copy metresPerUnit to sibling pages that
 * already have mark-up / Blake runs but no scale yet (drawing-level expectation).
 */
export function fillMissingPageScalesFromDocument(studio: StudioState): StudioState {
  const scales = [...studio.scales];
  const byDoc = new Map<string, StudioPageScale[]>();
  for (const row of scales) {
    if (!(row.metresPerUnit > 0)) continue;
    const list = byDoc.get(row.documentId) || [];
    list.push(row);
    byDoc.set(row.documentId, list);
  }
  if (!byDoc.size) return studio;

  const pagesNeeding = new Map<string, Set<number>>();
  for (const geo of studio.geometries) {
    if (geo.kind !== "linear" && geo.kind !== "area") continue;
    const set = pagesNeeding.get(geo.documentId) || new Set<number>();
    set.add(geo.page);
    pagesNeeding.set(geo.documentId, set);
  }
  // Always include any page that already has an explicit scale source page's siblings
  // for documents the user calibrated, even before mark-up exists.
  for (const [documentId, rows] of byDoc) {
    const set = pagesNeeding.get(documentId) || new Set<number>();
    for (const row of rows) set.add(row.page);
    pagesNeeding.set(documentId, set);
  }

  let changed = false;
  for (const [documentId, pages] of pagesNeeding) {
    const sources = byDoc.get(documentId);
    if (!sources?.length) continue;
    const preferred =
      sources.find((row) => row.knownMetres || row.calibrateFrom) ||
      sources.find((row) => Boolean(row.label)) ||
      sources[0];
    if (!preferred) continue;
    for (const page of pages) {
      const exists = scales.some((row) => row.documentId === documentId && row.page === page && row.metresPerUnit > 0);
      if (exists) continue;
      scales.push({
        documentId,
        page,
        metresPerUnit: preferred.metresPerUnit,
        label: preferred.label || (preferred.knownMetres ? `${preferred.knownMetres} m` : undefined),
      });
      changed = true;
    }
  }
  if (!changed) return studio;
  return { ...studio, scales, updatedAt: new Date().toISOString() };
}

/** Upsert one page scale; optionally copy metres to other pages of the same drawing that lack scale. */
export function upsertStudioPageScale(
  studio: StudioState,
  scale: StudioPageScale,
  options?: { applyToDocumentPages?: boolean },
): StudioState {
  const nextScales = [
    ...studio.scales.filter((row) => !(row.documentId === scale.documentId && row.page === scale.page)),
    scale,
  ];
  let next: StudioState = { ...studio, scales: nextScales, updatedAt: new Date().toISOString() };
  if (options?.applyToDocumentPages !== false) {
    next = fillMissingPageScalesFromDocument(next);
  }
  return next;
}

export function isAiStudioGeometry(geo: StudioGeometry): boolean {
  // Explicit manual accept/edit wins over ai-* id prefixes from Blake/vision.
  if (geo.source === "manual") return false;
  return geo.source === "ai" || geo.id.startsWith("ai-");
}

export function studioHasAiCounts(studio: StudioState): boolean {
  return studio.geometries.some((geo) => geo.kind === "count" && isAiStudioGeometry(geo))
    || Boolean(studio.aiReviewMeasured?.some((row) =>
      (row.tagMatches || []).some((match) => !match.excluded),
    ));
}

export function studioHasAiPipeRuns(studio: StudioState): boolean {
  return studio.geometries.some((geo) => geo.kind === "linear" && isAiStudioGeometry(geo));
}

/** Ensure preset coloured pipe/service classes exist (Hot/Cold/Heating/Waste…). Does not overwrite user colour edits. */
export function ensureServiceClassifications(studio: StudioState): StudioState {
  const classifications = [...studio.classifications];
  let changed = false;
  for (const def of SERVICE_CLASS_DEFS) {
    const idx = classifications.findIndex((cls) => cls.id === def.id);
    if (idx < 0) {
      const { role: _role, ...cls } = def;
      classifications.push(cls);
      changed = true;
      continue;
    }
    const existing = classifications[idx]!;
    let next = existing;
    // Backfill layer on older projects without changing colour the user may have edited.
    if (!existing.layer && def.layer) {
      next = { ...next, layer: def.layer };
    }
    // Backfill Draw-as group so older flat lists gain collapsible sections.
    if (!existing.group && def.group) {
      next = { ...next, group: def.group };
    }
    // Migrate Blake's old green "cold" swatch to standard plumbing blue (only exact prior default).
    if (def.id === "cls-ai-P-PIPE-C" && existing.colour.toLowerCase() === "#1f8f5f") {
      next = { ...next, colour: def.colour };
    }
    if (next !== existing) {
      classifications[idx] = next;
      changed = true;
    }
  }
  if (!changed) return studio;
  return { ...studio, classifications, updatedAt: new Date().toISOString() };
}

/** @deprecated alias — Blake pipe import path */
export function ensurePipeRunClassifications(studio: StudioState): StudioState {
  return ensureServiceClassifications(studio);
}

export function classificationLayer(cls: StudioClassification): StudioServiceLayerId {
  return cls.layer || "general";
}

export function classificationGroup(cls: StudioClassification): StudioClassGroupId {
  return cls.group || "general";
}

export type StudioClassificationGroupSection = {
  /** Stable key for accordion open state (unique when Master / all mixes layers). */
  key: string;
  groupId: StudioClassGroupId;
  label: string;
  items: StudioClassification[];
};

/**
 * Bucket Draw-as classifications into collapsible groups.
 * When `scopeLayer` is "all", prefixes each section with the service layer label
 * so Valves on Hot & cold stay separate from Radiators & valves on Heating.
 */
export function groupStudioClassifications(
  classifications: StudioClassification[],
  options?: {
    scopeLayer?: StudioServiceLayerId | "all";
    layerLabels?: Array<{ id: string; label: string }>;
  },
): StudioClassificationGroupSection[] {
  const scopeLayer = options?.scopeLayer || "all";
  const layerLabel = (layerId: string) =>
    options?.layerLabels?.find((row) => row.id === layerId)?.label
    || STUDIO_SERVICE_LAYERS.find((row) => row.id === layerId)?.label
    || layerId;

  const buckets = new Map<string, StudioClassificationGroupSection>();
  for (const cls of classifications) {
    const groupId = classificationGroup(cls);
    const layerId = classificationLayer(cls);
    const key = scopeLayer === "all" ? `${layerId}::${groupId}` : groupId;
    const label =
      scopeLayer === "all"
        ? `${layerLabel(layerId)} · ${studioClassGroupLabel(groupId)}`
        : studioClassGroupLabel(groupId);
    const existing = buckets.get(key);
    if (existing) {
      existing.items.push(cls);
    } else {
      buckets.set(key, { key, groupId, label, items: [cls] });
    }
  }

  const orderIndex = (groupId: StudioClassGroupId) => {
    const idx = STUDIO_CLASS_GROUPS.findIndex((row) => row.id === groupId);
    return idx >= 0 ? idx : STUDIO_CLASS_GROUPS.length;
  };

  return [...buckets.values()].sort((a, b) => {
    if (scopeLayer === "all") {
      const layerA = a.key.split("::")[0] || "";
      const layerB = b.key.split("::")[0] || "";
      if (layerA !== layerB) {
        const layerOrder = STUDIO_SERVICE_LAYERS.map((row) => row.id);
        const ai = layerOrder.indexOf(layerA as StudioBuiltinLayerId | "all");
        const bi = layerOrder.indexOf(layerB as StudioBuiltinLayerId | "all");
        const aRank = ai >= 0 ? ai : layerOrder.length;
        const bRank = bi >= 0 ? bi : layerOrder.length;
        if (aRank !== bRank) return aRank - bRank;
        return layerA.localeCompare(layerB);
      }
    }
    return orderIndex(a.groupId) - orderIndex(b.groupId);
  });
}

export function setStudioActiveLayer(
  studio: StudioState,
  layerId: StudioServiceLayerId | "all",
): StudioState {
  const next = ensureServiceClassifications(studio);
  if (layerId === "all") {
    return { ...next, activeLayerId: "all", updatedAt: new Date().toISOString() };
  }
  const inLayer = next.classifications.filter((cls) => classificationLayer(cls) === layerId);
  const keepActive = inLayer.some((cls) => cls.id === next.activeClassificationId);
  const preferred =
    inLayer.find((cls) => cls.kind === "linear")
    || inLayer[0]
    || next.classifications.find((cls) => cls.id === next.activeClassificationId);
  return {
    ...next,
    activeLayerId: layerId,
    activeClassificationId: keepActive ? next.activeClassificationId : preferred?.id,
    tool: preferred?.kind || next.tool,
    updatedAt: new Date().toISOString(),
  };
}

export function setClassificationColour(
  studio: StudioState,
  classificationId: string,
  colour: string,
): StudioState {
  const nextColour = /^#?[0-9a-fA-F]{6}$/.test(colour.trim())
    ? (colour.startsWith("#") ? colour : `#${colour}`)
    : null;
  if (!nextColour) return studio;
  return {
    ...studio,
    classifications: studio.classifications.map((cls) =>
      cls.id === classificationId ? { ...cls, colour: nextColour } : cls,
    ),
    updatedAt: new Date().toISOString(),
  };
}

/** Apply the first scale ratio hint found in drawing text to every page that lacks a scale. */
export function applyScaleHintsToStudio(
  studio: StudioState,
  pages: Array<{ documentId: string; pageNumber: number; fullText?: string }>,
  renderScale = 1.35,
): { studio: StudioState; appliedLabel: string | null } {
  let appliedLabel: string | null = null;
  let metresPerUnit: number | null = null;
  for (const page of pages) {
    const hints = detectScaleRatioHints(page.fullText || "");
    if (!hints[0]) continue;
    const denom = parseScaleRatioLabel(hints[0]);
    if (!denom) continue;
    metresPerUnit = metresPerUnitFromRatio(denom, renderScale);
    appliedLabel = hints[0];
    break;
  }
  if (!metresPerUnit || !appliedLabel) return { studio, appliedLabel: null };

  const scales = [...studio.scales];
  for (const page of pages) {
    const exists = scales.some((row) => row.documentId === page.documentId && row.page === page.pageNumber);
    if (exists) continue;
    scales.push({
      documentId: page.documentId,
      page: page.pageNumber,
      metresPerUnit,
      label: appliedLabel,
    });
  }
  return {
    studio: { ...studio, scales, updatedAt: new Date().toISOString() },
    appliedLabel,
  };
}

export function importPipeRunsIntoStudio(
  studio: StudioState,
  runs: Array<{
    documentId: string;
    pageNumber: number;
    points: StudioPoint[];
    role: "hot" | "cold" | "waste" | "other";
    pageHeight: number;
    colourHex?: string;
  }>,
  options?: {
    renderScale?: number;
    replaceExistingAiPipes?: boolean;
    aiReviewStatus?: StudioAiReviewStatus;
    /** Size Blake runs (e.g. cu-22) so BOQ + fittings resolve. */
    pipeSpec?: { id: string; material: string; diameter: string; stockLengthM: number };
    wastePipeSpec?: { id: string; material: string; diameter: string; stockLengthM: number };
  },
): StudioState {
  const renderScale = options?.renderScale ?? 1.35;
  let next = ensurePipeRunClassifications(studio);
  let keep = next.geometries;
  if (options?.replaceExistingAiPipes) {
    // Only wipe measured Blake pipes (ai-pipe-*), never design-propose stubs (ai-propose-*).
    const removedPipeIds = new Set(
      next.geometries
        .filter((geo) => geo.kind === "linear" && geo.id.startsWith("ai-pipe-"))
        .map((geo) => geo.id),
    );
    keep = next.geometries.filter((geo) => {
      if (geo.kind === "linear" && geo.id.startsWith("ai-pipe-")) return false;
      if (
        geo.kind === "count"
        && geo.autoGenerated
        && geo.linkedLinearId
        && removedPipeIds.has(geo.linkedLinearId)
      ) {
        return false;
      }
      return true;
    });
  }
  const geometries = [...keep];

  for (const [index, run] of runs.entries()) {
    if (run.role === "other" || run.points.length < 2) continue;
    const def = PIPE_CLASS_DEFS.find((row) => row.role === run.role);
    if (!def) continue;
    const points = run.points.map((point) => ({
      x: point.x * renderScale,
      y: (run.pageHeight - point.y) * renderScale,
    }));
    const sized = run.role === "waste" ? options?.wastePipeSpec : options?.pipeSpec;
    geometries.push({
      id: `ai-pipe-${run.documentId}-${run.pageNumber}-${index}`,
      classificationId: def.id,
      kind: "linear",
      documentId: run.documentId,
      page: run.pageNumber,
      points,
      source: "ai",
      confidence: "Medium",
      reviewStatus: options?.aiReviewStatus ?? "pending",
      notes: `Blake vector stroke · ${run.colourHex || run.role}`,
      material: sized?.material,
      diameter: sized?.diameter,
      stockLengthM: sized?.stockLengthM,
      pipeSpecId: sized?.id,
    });
  }

  const firstPipe = geometries.find((geo) => geo.kind === "linear" && isAiStudioGeometry(geo));
  return {
    ...next,
    geometries,
    activeDocumentId: firstPipe?.documentId || next.activeDocumentId,
    activePage: firstPipe?.page || next.activePage,
    activeClassificationId: firstPipe?.classificationId || next.activeClassificationId,
    tool: firstPipe ? "select" : next.tool,
    updatedAt: new Date().toISOString(),
  };
}

/** Hard review gate — only real AI count pins block Core push. Pipe runs live on the sheet/BOQ. */
export function studioNeedsAiReview(studio: StudioState): boolean {
  return studio.aiReviewStatus === "pending" && studioHasAiCounts(studio);
}

export function countAiStudioPipeRuns(studio: StudioState): number {
  return studio.geometries.filter((geo) => geo.kind === "linear" && isAiStudioGeometry(geo)).length;
}

export function countAiStudioCountPins(studio: StudioState): number {
  return studio.geometries.filter((geo) => geo.kind === "count" && isAiStudioGeometry(geo) && !geo.autoGenerated).length;
}

export type StudioQuantityRow = {
  classificationId: string;
  name: string;
  kind: StudioClassKind;
  colour: string;
  quantity: number;
  unit: string;
  pieces: number;
};

export function summariseStudioQuantities(studio: StudioState): StudioQuantityRow[] {
  return studio.classifications.map((cls) => {
    const items = studio.geometries.filter((geo) => geo.classificationId === cls.id);
    let quantity = 0;
    for (const geo of items) {
      const scale = scaleForPage(studio, geo.documentId, geo.page);
      const mpu = scale?.metresPerUnit || 0;
      if (geo.kind === "count") {
        quantity += 1;
      } else if (geo.kind === "linear") {
        quantity += linearMeasuredMetresForGeo(geo.points, mpu, geo);
      } else if (geo.kind === "area" && geo.closed) {
        quantity += polygonArea(geo.points) * mpu * mpu;
      }
    }
    return {
      classificationId: cls.id,
      name: cls.name,
      kind: cls.kind,
      colour: cls.colour,
      quantity: cls.kind === "count" ? quantity : Number(quantity.toFixed(2)),
      unit: cls.unit,
      pieces: items.length,
    };
  });
}

export function studioQuantitiesToMaterialAllowances(
  studio: StudioState,
  projectId: string,
): Array<{
  id: string;
  section: string;
  description: string;
  quantity: number;
  unit: string;
  unitCost: number;
  markupPercent: number;
  supplierRequired: boolean;
}> {
  const sizedLinearIds = new Set(
    studio.geometries
      .filter((geo) => geo.kind === "linear" && (geo.material || geo.diameter))
      .map((geo) => geo.classificationId),
  );
  const fittingClassIds = new Set(["cls-fit-90-elbow", "cls-fit-coupling"]);
  return summariseStudioQuantities(studio)
    .filter((row) => row.quantity > 0)
    .filter((row) => !sizedLinearIds.has(row.classificationId) && !fittingClassIds.has(row.classificationId))
    .map((row) => ({
      id: `studio-mat-${projectId}-${row.classificationId}`,
      section: row.kind === "area" ? "Areas" : row.kind === "linear" ? "Linears" : "Counts",
      description: `Takeoff · ${row.name}`,
      quantity: row.quantity,
      unit: row.unit,
      unitCost: 0,
      markupPercent: 0,
      supplierRequired: false,
    }));
}

/** Import skill text-tag count pins onto the Studio canvas as Count classifications. */
export function importSkillCountsIntoStudio(
  studio: StudioState,
  measured: Array<{
    id: string;
    assemblyId?: string;
    kind: "primary" | "secondary";
    code: string;
    description: string;
    quantity?: number;
    unit: string;
    method?: string;
    confidence?: TakeoffConfidence;
    sourceSheetIds?: string[];
    tagMatches?: Array<{
      id: string;
      documentId: string;
      fileName?: string;
      pageNumber: number;
      text?: string;
      x: number;
      y: number;
      pageWidth?: number;
      pageHeight?: number;
      excluded?: boolean;
      manual?: boolean;
      derived?: boolean;
    }>;
  }>,
  options?: {
    canvasWidth?: number;
    canvasHeight?: number;
    replaceExistingAi?: boolean;
    aiReviewStatus?: StudioAiReviewStatus;
  },
): StudioState {
  const canvasW = options?.canvasWidth || 0;
  // Only replace measured AI count pins — keep pipe runs, fittings, and propose-* plant pins.
  const keep = options?.replaceExistingAi
    ? studio.geometries.filter((geo) => {
      if (geo.kind !== "count" || geo.autoGenerated) return true;
      if (!isAiStudioGeometry(geo)) return true;
      if (geo.id.startsWith("ai-propose-")) return true;
      return false;
    })
    : studio.geometries;

  const classifications = [...studio.classifications];
  const geometries = [...keep];

  for (const row of measured) {
    if (row.kind !== "primary" || row.unit !== "nr") continue;
    const matches = (row.tagMatches || []).filter((match) => !match.excluded);
    if (!matches.length) continue;

    let cls = classifications.find((item) => item.id === `cls-ai-${row.code}`);
    if (!cls) {
      cls = {
        id: `cls-ai-${row.code}`,
        kind: "count",
        name: row.description || row.code,
        colour: nextClassificationColour(classifications),
        unit: "nr",
        notes: `Imported from Blake · ${row.code}`,
      };
      classifications.push(cls);
    }

    for (const match of matches) {
      const pageHeight = match.pageHeight || 0;
      const renderScale =
        canvasW && match.pageWidth ? canvasW / match.pageWidth : 1.35;
      // PDF text transforms are origin bottom-left; Studio canvas is top-left at render scale.
      geometries.push({
        id: `ai-${match.id}`,
        classificationId: cls.id,
        kind: "count",
        documentId: match.documentId,
        page: match.pageNumber || 1,
        source: "ai",
        confidence: row.confidence,
        reviewStatus: options?.aiReviewStatus ?? studio.aiReviewStatus ?? "pending",
        sourceTagId: match.id,
        sourceText: match.text,
        point: {
          x: match.x * renderScale,
          y: pageHeight ? (pageHeight - match.y) * renderScale : match.y * renderScale,
        },
      });
    }
  }

  const firstAi = geometries.find((geo) => geo.id.startsWith("ai-"));
  const firstAiClass = classifications.find((c) => c.id.startsWith("cls-ai-"));

  return {
    ...studio,
    classifications,
    geometries,
    activeDocumentId: firstAi?.documentId || studio.activeDocumentId,
    activePage: firstAi?.page || studio.activePage,
    activeClassificationId: firstAiClass?.id || studio.activeClassificationId,
    tool: "select",
    aiReviewStatus: options?.aiReviewStatus ?? studio.aiReviewStatus,
    aiReviewMeasured: studio.aiReviewMeasured,
    aiReviewUpdatedAt: studio.aiReviewUpdatedAt,
    updatedAt: new Date().toISOString(),
  };
}
